= aero.minova.rcp

Der Standard RCP Fatclient von MINOVA

link:/REMARKS.adoc[Notizen]

== Funktionsumfang

Ich möchte diese Anwendung entsprechend erweitern.
Aktuell ist es das nackte RCP-Projekt mit einem Bespiel Part und einem weiteren Beispiel Plugin.

Als nächstes möchte ich die NatTable und JSON integrieren.
Dazu habe ich eine interessante Seite gefunden (https://www.vogella.com/tutorials/NatTableDataSources/article.html)

=== Workspace

Diese Anwendung soll eine Anwendung sein, die dann mehrfach geöffnet werden kann. 
Dabei hat jede Instanz seinen eigenen link:bundles/aero.minova.rcp.workspace/README.adoc[Workspace]
In den Workspaces werden auch zusätzliche Plug-ins gespeichert, die die Anwendung bereichern.

=== Masken

Wir wollen in dieser Anwendung auch Masken verwenden, ähnlich den heutigen Masken in TTA.
Dazu müssen wir wieder ein Schema definieren, dass es erlaubt entsprechende Masken zu definieren.
Das Schema ist link:bundles/aero.minova.rcp.form.model/README.adoc[hier] beschrieben.

=== Felder

Auf den Masken gibt es die unterschiedlichen Felder.
Die Datentypen sollen entsprechend behandelt werden.

Für link:bundles/aero.minova.rcp.rcp/README.adoc[Datum-/Zeit-Felder] gibt es eine eigene Dokumentation.

== Releaseprozess

Der Releaseprozess funktioniert.
Aktueller Releaseprozess findet sich link:releng/aero.minova.rcp.product/README.adoc[hier]!


=== Maven

Wir können ein Release mit Maven bauen.
Da das Release auf unserem link:http://minnexus.minova.com:8081/nexus/#view-repositories;releases~browsestorage[Nexus] gespeichert wird, muss eine Verbindung dahin existieren.

Wir haben 3 unterschiedliche Releases

==== Target Platform

Die Target Platform befindet sich im Ordner `releng/target-definition`.
Der aktuelle Release befindet sich auf Nexus und kann in der Regel verendet werden.

Wenn man weitere Plugins von anderen öffentlichen Projekten verwenden will, muss man diese in der Target Platform ergänzen und dann einen neuen Release bauen.

[source,sh]
----
$ cd releng/target-definition <1>

$ mvn release:prepare <2>
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< aero.minova.rcp:eclipse-2019-03 >-------------------
[INFO] Building eclipse-2019-03 1.0.2-SNAPSHOT
[INFO] ---------------------[ eclipse-target-definition ]----------------------
[INFO] 
...
[INFO] Working directory: /Users/saak/git/aero.minova.rcp/releng/target-definition
[WARNING] Ignoring unrecognized line: ?? releng/target-definition/release.properties
[INFO] Checking dependencies and plugins for snapshots ...
What is the release version for "eclipse-2019-03"? (aero.minova.rcp:eclipse-2019-03) 1.0.2: : 1.1.0 <3>
What is SCM release tag or label for "eclipse-2019-03"? (aero.minova.rcp:eclipse-2019-03) eclipse-2019-03-1.1.0: : <4>
What is the new development version for "eclipse-2019-03"? (aero.minova.rcp:eclipse-2019-03) 1.1.1-SNAPSHOT: : <5>
[INFO] Transforming 'eclipse-2019-03'...
...
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.447 s
[INFO] Finished at: 2020-01-25T08:01:20+01:00
[INFO] ------------------------------------------------------------------------

$ mvn release:perform <6>
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< aero.minova.rcp:eclipse-2019-03 >-------------------
[INFO] Building eclipse-2019-03 1.1.1-SNAPSHOT
[INFO] ---------------------[ eclipse-target-definition ]----------------------
[INFO] 
...
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.853 s
[INFO] Finished at: 2020-01-25T08:02:05+01:00
[INFO] ------------------------------------------------------------------------
----

<1> Im Ordner `releng/target-definition` befindet sich die Definition der Target Platform. 
Diese sollte man auch immer bei der Entwicklung verwenden.

<2> Mit diesem Befehl starten wir den Release-Prozess.
Dazu müssen das lokale Git und das remote Git synchron sein (`git push` /  `git pull`).
Wenn man keine weiteren Parameter angibt, wird man interaktiv gefragt.

<3> Versionsnummer des Release eingeben.
Wenn man nicht den Parameter `-DreleaseVersion=1.1.0` in 2 angegeben hat, kann man hier die Versionsnummer angeben.

* Major hochzählen, wenn wir nicht mehr abwärtskompatibel sind!

* Minor hochzählen, wenn wir die Software funktional für den Endanwender erweitert haben.

* Patchlevel hochzählen, wenn wir nur einen Fehler behoben haben.
Dabei kann es vorkommen, dass wir vielen neue Module integriert haben.
Wenn diese aber keine Erweiterung der Funktionalität für den Anwender bedeuten, bleibt es eine Fehlerkorrektur oder Verschönerung.

<4> Das Tag für den neuen Release.
In der Regel wird die `ArtefactID` und die Releasenummer (`1.1.0`) mit einem `-` getrennt vorgeschlagen.
Das ist auch soweit OK. +
Die Frage kann man umgehen, wenn man den Parameter `-Dtag=eclipse-2019-03-1.1.0` übergeben würde.

<5> Die neue Entwickllungsversion.
Sie muss immer mit `-SNAPSHOT` enden.
Dies ist der Standard von Maven.
Tycho ändert dies in den Eclipsekonfigurationen auf `.qualifier` um. +
Als nächste Version gehen wir immer von einer Fehlerkorrektur aus.
Deshalb in diesem Beispiel `1.1.1-SNAPSHOT`. +
Die Frage kann man umgehen, wenn man den Parameter `-DdevelopmentVersion=1.1.1-SNAPSHOT` übergeben würde.

<6> Als letztes können wir dann das Release bauen und ausliefern lassen.
Dazu ist die Verbindung zum Nexus erforderlich.

==== Konfiguration

Als nächsten kann man die Konfiguration für alle Eclipse Plugins / Module releasen.
Sie befindet sich im Ordner `releng/aero.minova.rcp.configuration`.

Sie enthält den Verweis auf die Target Platform.

include::releng/aero.minova.rcp.configuration/pom.xml[tags=target-definition]

Deshalb muss die Version immer neu gesetzt werden, sobald die Target Plattform verändert wird.
Danach muss man auch die Konfiguration neu releasen.

==== Root

[WARNING]
Das Root-Projekt wird auf dem Jenkins gebaut.

link:http://minjenkins.minova.com:8080/job/release-aero.minova.rcp/[http://minjenkins.minova.com:8080/job/release-aero.minova.rcp/]


Als letztes kann man dann das Root-Projekt releasen.
Es hat einen Verweis auf die Konfiguration.

include::pom.xml[tags=parent]

Die Version sollte der letzten Release-Version von der Konfiguration entsprechen.
Dann kann man eine neue Version vom Produkt erstellen.
Dazu sind folgende Schritte erforderlich.

===== Versionsnummer ermitteln

Als erstes sollte man die neue Versionsnummer festlegen.
Die letzten Releases kann man sich auf der Kommandozeile leicht anzeigen lassen.

[bash]
.Realeses anzeigen
----
$ git tag -l
eclipse-2019-03-1.0.0
eclipse-2019-03-1.0.1
eclipse-2019-03-1.1.0
eclipse-2019-03-1.2.0
aero.minova.rcp.configuration-1.0.0
aero.minova.rcp.configuration-1.0.1
aero.minova.rcp.configuration-1.0.2
aero.minova.rcp.configuration-1.0.3
aero.minova.rcp.configuration-1.0.4
aero.minova.rcp.configuration-1.1.0
aero.minova.rcp.configuration-1.2.0
aero.minova.rcp.root-1.0.1
aero.minova.rcp.root-1.0.2
aero.minova.rcp.root-1.0.3
aero.minova.rcp.root-1.1.0
aero.minova.rcp.root-1.2.0
----

Jedes Release verfügt über ein eigenes Tag.
Das Root-Projekt hat die Tags, die mit `aero.minova.rcp.root-` beginnen.
In unserem Fall ist die letzte Version des Products 1.2.0.

Die neue Version enthält eine neue Funktionalität.
Deshalb inkrementieren wir die Minor Version (auf 1.3.0).

===== Build vorbereiten

Den Buildprozess in Maven stoßen wir mit mehreren Parametern an, weil wir sonst sehr oft noch der neuen Version gefragt werden.

.Root-Projekt releasen
[bash]
----
$ mvn release:prepare \
  -DreleaseVersion=1.3.0 \ <1>
  -DdevelopmentVersion=1.3.1-SNAPSHOT \ <2>
  -Dtag=aero.minova.rcp.root-1.3.0 <3>
----

<1> Die Version des Releases können wir mit dem Parameter `releaseVersion` festlegen.
Damit werden wird nicht gefragt.
Ist er nicht angegeben, werden wir für jedes Projekt gefragt. 

<2> Die Version des nächsten SNAPSHOT können wir mit dem Parameter `developmentVersion` festlegen.
Damit werden wird nicht gefragt.
Ist er nicht angegeben, werden wir für jedes Projekt gefragt. 
[IMPORTANT]
Dieser Wert muss immer mit `-SNAPSHOT` enden.
Tycho modofiziert damit auch die OSGi-Dateien.
Und dort heißt es dann `.qualifier`.

<3> Für das Release benötigen wir auch einen Tag.
Beim ersten Mal wurde der Projektname des Root-Projektes genommen, weil wir in dem Verzeichnis den Release-Prozess gestartet haben.
Wenn man es mal irgendwo konfiguriert, könnte man auch als Tagnamen den Namen des Produktprojektes (`aero.minova.rcp.product`) verwenden.

===== Build abschließen

Sobald die Vorbereitung erfolgreich war, kann man den Build abschließen.
Damit wird er dann auch auf unserem link:http://nexus.minova.com:8081/nexus/#view-repositories;releases~browsestorage~name/saak/tycho/aero.minova.rcp.product[Nexus] gespeichert.

.Root-Projekt releasen
[bash]
----
$ mvn release:perform
----

Damit sollte das Projekt ein neues Release im Nexus erhalten haben.

Wenn man der Release interaktiv (auf dem Terminal) erstellt hat, kann es passieren, dass man nochmals das Git pushen muss.

.Repository nach GitHub pushen
[bash]
----
$ git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 412 bytes | 206.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/ingraban/rcp.git
   41ef823..eaa7c30  master -> master
----


=== Tycho

Ich habe es mit Tycho Version 1.4.0 geschafft.

Mit 1.5.0 hatte ich Probleme. 
Diese können aber auch daher rühren, dass ich noch einige Bundles pomless erstellt habe.

==== POM First

Bei mir hat es nur funktioniert, wenn ich dem POM First Ansatz verfolgt habe.
Man muss für jedes Projekt ein pom.xml anlegen.

==== Versionierung

Die Version (-SNAPSHOT / .qualifier) muss in allen Projekten gleich sein.
Das macht aber auch Sinn, da man ja immer eine Version der Anwendung erstellt.

Wir haben 2 Projekte aus diesem Prozess herausgenommen.

==== Target Definition

Die Targetdefinition wird sich in aller Regel nicht so oft ändern. 
Aus diesem Grund wird sie standalone released.

So muss man sie auch nur einmal erstellen und bei sich setzen.

==== Configuration

Die Configuration habe ich auch standalone erstellt / released.

= Weitere Dokumentationen

* link:releng/aero.minova.rcp.product/README.adoc[Aktueller Releaseprozess]
* link:PluginErstellen.adoc[Erstellen von neuen Plugins (für Helper, Ersatz von JavaScript in Masken)]
* link:Updatesite.adoc[Erstellen und Nutzen von der Updatesite]
* link:bundles/aero.minova.rcp.preferences/README.adoc[Einstellungen]
* link:bundles/aero.minova.rcp.rcp/README.adoc[UI Eigenschaften]
* link:bundles/aero.minova.rcp.dataservice/README.adoc[Verhalten wenn CAS nicht erreichbar ist]


