== XMLForm.xsd

In diesem Schema wird die Maske beschrieben.
Diese Dokumentation wird Stück für Stück ergänzt.
Dadurch kann das Wissen immer wieder nachgetragen werden.

=== <form>

Jede Maske wird durch ein Tag `<form>` beschrieben.
Neben den unten beschriebenen Attributen kann es noch folgende Elemente besitzen.

* link:#index-view[<index-view>]
* link:#detail[<detail>]
* link:#events[<events>]

==== icon

==== title

==== helper-class

=== <index-view>

=== <detail>

=== <events> 

=== <column>

=== <field>

Im link:#head[`<Head>`] und in der link:#page[`<Page>`] werden die einzelnen Felder definiert.
Als Element ist genau ein Kind möglich, dass den Datentyp beschreibt.

* link:#lookup[<lookup>]

=== <head>

=== <page>

=== Datentypen

==== <lookup>

Eine Lookup-Spalte speichert als Wert immer einen Integer.
Dies ist der `KeyLong` der referenzierten Tabelle.
Angezeigt wird jedoch in der Regel der `KeyText` der referenzierten Tabelle - dies ist ja auch der Benutzerschlüssel.

Zusätzlich kann noch rechts neben dem Feld die Beschreibung angezeigt werden.
Dies ist ist der Regel der Wert aus der Spalte `Description` in der referenzierten Tabelle.
Wenn eine View verwendet wird, oder eine gespeicherte Prozedur, dann kann es auch einen anderen Wert - z.B. eine Berechnung - anzeigen.

===== procedure-prefix

Wenn dieses Attribut gesetzt ist, werden die Daten der referenzierten Tabelle mittels gespeicherter Prozeduren ermittelt.
Dabei gibt es 2 Prozeduren.

====== List

Diese Prozedur liefert die möglichen Werte.
Als Aufrufparameter werden folgende Parameter übergeben.

[horizontal]
Count int output:: 
Dieser Wert wird von der Prozedur zurückgegeben.
Er enthält die Anzehl der gefundenen Werte.

FilterLastAction bit:: 
Mit diesem Wert kann unter Umständen (wenn es die Prozedur berücksichtigt) das Löschkennzeichen berücksichtigt werden.
Wird eine 1 (`true`) übergeben, sollen die gelöschten Werte (`LastAction < 0`) nicht zurückgegeben werden.
Wird eine 0 (`false`) übergeben, sollen alle Werte zurückgegeben werden.

`param`::
Jetzt werden in der definierten Reihenfolge die Werte der Parameter übergeben.
Dabei muss auch der Wert `null` möglich sein.
Der Datentyp orientiert sich an dem Datentyp der entsprechenden Spalte. 

====== Resolve


===== table

===== key-long-name

Default ist `KeyLong`

===== key-text-name

Default ist `KeyText`

===== description-name

Default ist `Description`

===== filter-blocked

Default ist `false`

===== filter-last-action

Default ist `true`

===== form

Dieses Attribut diente mal dazu, dass man eine Maske öffnen kann, in der man Daten suchen oder auch neu anlegen kann.
Dieses Attribut wird aktuell nicht ausgewertet.

===== use-resolve-params

Dieses Attribut wird aktuell nicht ausgewertet.
Es dient in Verbindung mit link:#procedure-prefix[procedure-prefix] dazu, dass beim Auflösen von interne Schlüssel (`KeyLong`) in Benutzerschlüssel (`KeyText`) alle Parameter mit übergeben werden.

