=== Ordnerstruktur

Der Workspace einer Serververbindung wird immer unter dem Ordner `%user.home/.minwfc/` angelegt.
Unter Linux und macOS sind diese Ordner nit sichtbar. 

Die Ordnerstruktur im Workspace des WFC ist wie folgt gegliedert.

==== .metadata

Dieser Ordner wird von Eclipse RCP angelegt und verwaltet.
In diesem Ordner befinden sich unter anderem auch die Einstellungen, die der Anwender für diese Instanz vorgenommen hat.

Zu den Einstellungen gehören vor allen Dingen die Propertionen der Masken, die Reihenfolge der OptionPages und ähnliches.

==== plugins

Im diesem Ordner werden alle Plug-ins gespeichert, die vom Server geliefert werden.
Dieses Plug-in lädt und startet die Plug-ins, sobald es dazu programmatisch aufgefordert wird.

==== i18n

In diesem Ordner werden die Dateien gespeichert, die für die Internationalisierung von Server geladen werden.

==== config

In diesem Ordner wird aktuell die XBS und die MDI gespeichert. 

In diesem Ordner werden auch die Masken gespeichert.
Sie entsprechen dem Aufbau nach den heute von MINOVA erstellen Masken und OptionPages.

==== data

Dieser Ordner ist als Speicherort für Daten vorgesehen.
Es soll die Möglichkeit existieren, dass gewisse Daten offline gespeichert werden.

