# This workflow will build the Eclipse RCP application with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean verify surefire-report:report --fae --file pom.xml -T4

#    - uses: actions/upload-artifact@v2
#      with:
#        name: minova-wfc-linux
#        path: /home/runner/work/aero.minova.rcp/aero.minova.rcp/releng/aero.minova.rcp.product/target/products/*linux*.zip
#    - uses: actions/upload-artifact@v2
#      with:
#        name: minova-wfc-mac
#        path: /home/runner/work/aero.minova.rcp/aero.minova.rcp/releng/aero.minova.rcp.product/target/products/*mac*.zip
#    - uses: actions/upload-artifact@v2
#      with:
#        name: minova-wfc-win
#        path: /home/runner/work/aero.minova.rcp/aero.minova.rcp/releng/aero.minova.rcp.product/target/products/*win*.zip
    
